require('which-key').setup {
  -- delay between pressing a key and opening which-key (milliseconds)
  -- this setting is independent of vim.o.timeoutlen
  delay = 250,
  preset = 'helix',
  icons = {
    rules = {
      { pattern = 'change', icon = ' ', color = 'blue' },
      { pattern = 'clocks', icon = ' ', color = 'green' },
      { pattern = 'delete', icon = '󰆴 ', color = 'red' },
      { pattern = 'diff', icon = ' ', color = 'yellow' },
      { pattern = 'execute', icon = ' ', color = 'blue' },
      { pattern = 'file', icon = ' ', color = 'white' },
      { pattern = 'go', icon = '󰬫 ', color = 'blue' },
      { pattern = 'grep', icon = '󱎸 ', color = 'green' },
      { pattern = 'history', icon = ' ', color = 'red' },
      { pattern = 'hook', icon = '󰛢 ', color = 'orange' },
      { pattern = 'lua', icon = ' ' },
      { pattern = 'mark', icon = '󰍕 ', color = 'blue' },
      { pattern = 'oil', icon = ' ', color = 'yellow' },
      { pattern = 'org', icon = ' ' },
      { pattern = 'plugin', icon = ' ', color = 'blue' },
      { pattern = 'reel', icon = '🎣 ', color = 'orange' },
      { pattern = 'register', icon = '󰠷 ', color = 'blue' },
      { pattern = 'remote', icon = ' ', color = 'red' },
      { pattern = 'remove', icon = ' ', color = 'red' },
      { pattern = 'replace', icon = ' ', color = 'yellow' },
      { pattern = 'unhook', icon = '󰛣 ', color = 'red' },
    },
  },

  -- Document existing key chains
  spec = {
    { '<leader>b', group = 'Buffer' },
    { '<leader>c', group = 'Code' },
    { '<leader>d', group = 'Diff/Del/Debug' },
    { '<leader>f', group = 'Find' },
    { '<leader>g', group = 'Git' },
    { '<leader>h', group = 'Git Hunk' },
    { '<leader>j', group = 'Hook files' },
    { '<leader>k', group = 'Clocks' },
    { '<leader>m', group = 'Macro/Registers' },
    { '<leader>o', group = 'Org mode' },
    { '<leader>p', group = 'Plugin' },
    { '<leader>q', group = 'Sessions' },
    { '<leader>r', group = 'Remote' },
    { '<leader>s', group = 'Search' },
    { '<leader>t', group = 'Terminal' },
    { '<leader>u', group = 'UI + Toggles' },
    { '<leader>uF', group = 'Folding' },
    { '<leader>x', group = 'Execute' },
  },
}
